In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

## Parsing the Excel file

The first header's row only contains the timestamp starting from 00:00 with an increment of 15 minutes.

We can ignore it since we can re-calculate the value from the id of velocity and remove that header increase in the readability of the table.

In [2]:
df = pd.read_excel("data/Scats Data October 2006.xls", sheet_name="Data", header=[1])
df

SCATS Number                         Location CD_MELWAY  NB_LATITUDE  \
0              970  WARRIGAL_RD N of HIGH STREET_RD   060 G10    -37.86703   
1              970  WARRIGAL_RD N of HIGH STREET_RD   060 G10    -37.86703   
2              970  WARRIGAL_RD N of HIGH STREET_RD   060 G10    -37.86703   
3              970  WARRIGAL_RD N of HIGH STREET_RD   060 G10    -37.86703   
4              970  WARRIGAL_RD N of HIGH STREET_RD   060 G10    -37.86703   
...            ...                              ...       ...          ...   
4187          4821      VICTORIA_ST W OF BURNLEY_ST   002HF02    -37.81296   
4188          4821      VICTORIA_ST W OF BURNLEY_ST   002HF02    -37.81296   
4189          4821      VICTORIA_ST W OF BURNLEY_ST   002HF02    -37.81296   
4190          4821      VICTORIA_ST W OF BURNLEY_ST   002HF02    -37.81296   
4191          4821      VICTORIA_ST W OF BURNLEY_ST   002HF02    -37.81296   

      NB_LONGITUDE  HF VicRoads Internal  VR Internal Stat  VR Internal Loc  \
0        145.09159                   249               182                1   
1        145.09159                   249               182                1   
2        145.09159                   249               182                1   
3        145.09159                   249               182                1   
4        145.09159                   249               182                1   
...            ...                   ...               ...              ...   
4187     145.00830                  6673              1513                7   
4188     145.00830                  6673              1513                7   
4189     145.00830                  6673              1513                7   
4190     145.00830                  6673              1513                7   
4191     145.00830                  6673              1513                7   

      NB_TYPE_SURVEY                Date  ...  V86  V87  V88  V89  V90  V91  \
0                  1 2006-10-01 00:15:00  ...  114   97   97   66   81   50   
1                  1 2006-10-02 00:15:00  ...  111  102  107  114   80   60   
2                  1 2006-10-03 00:15:00  ...  130  132  114   86   93   90   
3                  1 2006-10-04 00:15:00  ...  115  113  132  101  113   90   
4                  1 2006-10-05 00:15:00  ...  171  120  116  113   99   91   
...              ...                 ...  ...  ...  ...  ...  ...  ...  ...   
4187               1 2006-10-27 00:15:00  ...  122  121  127  103  122  124   
4188               1 2006-10-28 00:15:00  ...   93   93   93  105  105  112   
4189               1 2006-10-29 00:15:00  ...   87  118   83   76   66   64   
4190               1 2006-10-30 00:15:00  ...   90   88   89   80   74   48   
4191               1 2006-10-31 00:15:00  ...  123  103   93   87   74   87   

      V92  V93  V94  V95  
0      59   47   29   34  
1      62   48   44   26  
2      73   57   29   40  
3      78   66   52   44  
4      61   55   49   36  
...   ...  ...  ...  ...  
4187  117   99  108   88  
4188   82   97  106  107  
4189   77   60   49   45  
4190   67   62   50   62  
4191   75   63   51   54  

[4192 rows x 106 columns]

## Getting the positon of the first collums of velocity

Return the array of arrays containing velocity from V00 to V95

In [3]:

first_velo_col_pos = df.columns.get_loc("V00")
flow_data = df.to_numpy()[:, first_velo_col_pos:]
flow_data

array([[86, 83, 52, ..., 47, 29, 34],
       [32, 28, 17, ..., 48, 44, 26],
       [26, 32, 21, ..., 57, 29, 40],
       ...,
       [100, 81, 89, ..., 60, 49, 45],
       [40, 29, 36, ..., 62, 50, 62],
       [36, 30, 24, ..., 63, 51, 54]], dtype=object)

In [4]:
flow_scaler = MinMaxScaler(feature_range=(0, 1)).fit(flow_data)
flow_values = flow_scaler.transform(flow_data)
flow_values

array([[0.28289474, 0.32936508, 0.25870647, ..., 0.21266968, 0.10394265,
        0.16037736],
       [0.10526316, 0.11111111, 0.08457711, ..., 0.21719457, 0.15770609,
        0.12264151],
       [0.08552632, 0.12698413, 0.10447761, ..., 0.25791855, 0.10394265,
        0.18867925],
       ...,
       [0.32894737, 0.32142857, 0.44278607, ..., 0.27149321, 0.17562724,
        0.21226415],
       [0.13157895, 0.11507937, 0.17910448, ..., 0.28054299, 0.17921147,
        0.29245283],
       [0.11842105, 0.11904762, 0.11940299, ..., 0.28506787, 0.1827957 ,
        0.25471698]])

In [5]:
lat_data = df['NB_LATITUDE'].to_numpy().reshape(-1, 1)
long_data = df['NB_LONGITUDE'].to_numpy().reshape(-1, 1)
np.concatenate((lat_data, long_data), axis=1)

array([[-37.86703, 145.09159],
       [-37.86703, 145.09159],
       [-37.86703, 145.09159],
       ...,
       [-37.81296, 145.0083 ],
       [-37.81296, 145.0083 ],
       [-37.81296, 145.0083 ]])

In [12]:
latlong_data = np.concatenate((lat_data, long_data), axis=1)
scaler = MinMaxScaler(feature_range=(0, 1)).fit(latlong_data)
latlong = scaler.transform(latlong_data)
latlong

array([[1.50524459e-05, 9.99949965e-01],
       [1.50524459e-05, 9.99949965e-01],
       [1.50524459e-05, 9.99949965e-01],
       ...,
       [1.44292218e-03, 9.99375943e-01],
       [1.44292218e-03, 9.99375943e-01],
       [1.44292218e-03, 9.99375943e-01]])

In [155]:
num_time_steps = 96

In [156]:
time_values = np.arange(num_time_steps) * 15 / 24 / 60
time_column = np.tile(time_values, len(flow_values)).reshape(-1, 1)
time_column

array([[0.        ],
       [0.01041667],
       [0.02083333],
       ...,
       [0.96875   ],
       [0.97916667],
       [0.98958333]])

In [93]:
expanded_latlong = np.repeat(latlong, num_time_steps, axis=0).reshape(-1, 2)
expanded_latlong

array([[1.50524459e-05, 9.99949965e-01],
       [1.50524459e-05, 9.99949965e-01],
       [1.50524459e-05, 9.99949965e-01],
       ...,
       [1.44292218e-03, 9.99375943e-01],
       [1.44292218e-03, 9.99375943e-01],
       [1.44292218e-03, 9.99375943e-01]])

In [146]:
shifted_flow_values = np.roll(flow_values, -1, axis=1)
shifted_flow_column = shifted_flow_values.reshape(-1, 1)
shifted_flow_column

array([[0.32936508],
       [0.25870647],
       [0.20640569],
       ...,
       [0.1827957 ],
       [0.25471698],
       [0.11842105]])

In [152]:
train = np.hstack((time_column, expanded_latlong, shifted_flow_column))
train

array([[0.00000000e+00, 1.50524459e-05, 9.99949965e-01, 3.29365079e-01],
       [1.04166667e-02, 1.50524459e-05, 9.99949965e-01, 2.58706468e-01],
       [2.08333333e-02, 1.50524459e-05, 9.99949965e-01, 2.06405694e-01],
       ...,
       [9.68750000e-01, 1.44292218e-03, 9.99375943e-01, 1.82795699e-01],
       [9.79166667e-01, 1.44292218e-03, 9.99375943e-01, 2.54716981e-01],
       [9.89583333e-01, 1.44292218e-03, 9.99375943e-01, 1.18421053e-01]])

In [153]:
X = train[:, :-1]
y = train[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, train_size = .75)

(X_train, y_train, X_test, y_test)

(array([[6.25000000e-02, 1.40489495e-03, 9.99873190e-01],
        [2.39583333e-01, 1.92486453e-03, 9.99740522e-01],
        [1.04166667e-01, 1.94202960e-03, 9.99793244e-01],
        ...,
        [6.14583333e-01, 7.81934952e-04, 9.99985941e-01],
        [6.66666667e-01, 1.12338780e-03, 9.99856305e-01],
        [4.89583333e-01, 1.17910826e-03, 9.99484283e-01]]),
 array([0.05825243, 0.01818182, 0.04950495, ..., 0.43074004, 0.2296173 ,
        0.22940226]),
 array([[1.35416667e-01, 1.72574972e-03, 9.99737834e-01],
        [7.91666667e-01, 2.25820226e-03, 9.99855103e-01],
        [4.37500000e-01, 1.72284486e-03, 9.99743761e-01],
        ...,
        [0.00000000e+00, 9.67845863e-04, 9.99544655e-01],
        [5.31250000e-01, 9.67845863e-04, 9.99544655e-01],
        [6.56250000e-01, 1.67134965e-03, 9.99883666e-01]]),
 array([0.03191489, 0.37157107, 0.22068966, ..., 0.03571429, 0.18979592,
        0.22638436]))