In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [5]:
df = pd.read_csv("data/train.csv")
df


5 Minutes  Lane 1 Flow (Veh/5 Minutes)  # Lane Points  % Observed
0      04/01/2016 0:00                           12              1         100
1      04/01/2016 0:05                           13              1         100
2      04/01/2016 0:10                           11              1         100
3      04/01/2016 0:15                           13              1         100
4      04/01/2016 0:20                           10              1         100
...                ...                          ...            ...         ...
7771  29/02/2016 23:35                           19              1         100
7772  29/02/2016 23:40                            6              1         100
7773  29/02/2016 23:45                           14              1         100
7774  29/02/2016 23:50                           11              1         100
7775  29/02/2016 23:55                           10              1         100

[7776 rows x 4 columns]

In [6]:

attr = 'Lane 1 Flow (Veh/5 Minutes)'
scaler = MinMaxScaler(feature_range=(0, 1)).fit(df[attr].values.reshape(-1, 1))
flow = scaler.transform(df[attr].values.reshape(-1, 1)).reshape(1, -1)[0]
flow

array([0.06091371, 0.06598985, 0.05583756, ..., 0.07106599, 0.05583756,
       0.05076142])

In [63]:
lags = 12
train= []
for i in range(lags, len(flow)):
	train.append(flow[i - lags: i + 1])
indices = np.arange(lags, len(flow))
offsets = np.arange(-lags, 1)
train2 = flow[indices[:, np.newaxis] + offsets]
train2

array([[0.06091371, 0.06598985, 0.05583756, ..., 0.03553299, 0.04060914,
        0.04060914],
       [0.06598985, 0.05583756, 0.06598985, ..., 0.04060914, 0.04060914,
        0.06091371],
       [0.05583756, 0.06598985, 0.05076142, ..., 0.04060914, 0.06091371,
        0.03553299],
       ...,
       [0.08121827, 0.13705584, 0.10659898, ..., 0.0964467 , 0.03045685,
        0.07106599],
       [0.13705584, 0.10659898, 0.10152284, ..., 0.03045685, 0.07106599,
        0.05583756],
       [0.10659898, 0.10152284, 0.05583756, ..., 0.07106599, 0.05583756,
        0.05076142]])

In [60]:
tmp = 3
test = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
train = []
for i in range(tmp, len(test)):
	train.append(test[i - tmp: i + 1])
indices = np.arange(tmp, len(test)).reshape(-1, 1)
test[indices + np.arange(-tmp, 1)]
# train

[array([1, 2, 3, 4]),
 array([2, 3, 4, 5]),
 array([3, 4, 5, 6]),
 array([4, 5, 6, 7]),
 array([5, 6, 7, 8]),
 array([6, 7, 8, 9]),
 array([ 7,  8,  9, 10])]